name: Build, Test and Deploy
on:
  push:
    branches:
      - master
jobs:
    voter:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 12
            - name: write google-services.json
              run: echo "$GOOGLE_SERVICES_JSON" > portal/src/environment/google-services.json
              env:
                GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
            - name: build project
              run: ccd portal && npm i && ng build && cd ..
            - name: deploy to gCloud
              uses: w9jds/firebase-action@master
              with:
                args: deploy
              env:
                FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
